name: Base-Python

on:
  push:
    branches: ["main"]
    paths:
      - "base/python/**"
      - "base/gmpy2/**"
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY: challenge-base

jobs:
  build-python:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      NAME: python

    strategy:
      matrix:
        include:
          - tag: alpine
            dockerfile: Dockerfile
          - tag: 3.11-alpine
            dockerfile: Dockerfile.3.11
          - tag: 3.12-alpine
            dockerfile: Dockerfile.3.12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.NAME }}
          tags: |
            ${{ matrix.tag }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: base/${{ env.NAME }}
          file: base/${{ env.NAME }}/${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true

  build-gmpy2:
    runs-on: ubuntu-latest
    needs: build-python
    permissions:
      contents: read
      packages: write

    env:
      NAME: gmpy2
      TAG: alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Docker setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.NAME }}
          tags: |
            ${{ env.TAG }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: base/${{ env.NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

  prune-python:
    runs-on: ubuntu-latest
    needs: build-python
    permissions:
      contents: read
      packages: write

    steps:
      - name: Prune old packages
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ${{ env.REPOSITORY }}/python
          validate: true
          dry-run: false
          delete-untagged: true
          delete-ghost-images: true
          delete-partial-images: true

  prune-gmpy2:
    runs-on: ubuntu-latest
    needs: build-gmpy2
    permissions:
      contents: read
      packages: write

    steps:
      - name: Prune old packages
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: ${{ env.REPOSITORY }}/gmpy2
          validate: true
          dry-run: false
          delete-untagged: true
          delete-ghost-images: true
          delete-partial-images: true
